/*
 * ribbon-health
 *
 * An API for interacting with the data provided by Ribbon Health, including information about healthcare providers, locations, insurances, and more. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EditCustomProviderFilter409Response : Resource with given fields aready exists
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditCustomProviderFilter409Response {
    #[serde(rename = "error")]
    pub error: models::GetCustomProvider404ResponseError,
}

impl EditCustomProviderFilter409Response {
    /// Resource with given fields aready exists
    pub fn new(error: models::GetCustomProvider404ResponseError) -> EditCustomProviderFilter409Response {
        EditCustomProviderFilter409Response {
            error,
        }
    }
}

