/*
 * ribbon-health
 *
 * An API for interacting with the data provided by Ribbon Health, including information about healthcare providers, locations, insurances, and more. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditCustomLocationFilter200ResponseData {
    /// A UUID uniquely identifying this filter
    #[serde(rename = "uuid")]
    pub uuid: uuid::Uuid,
    #[serde(rename = "filter")]
    pub filter: models::EditCustomLocationFilter200ResponseDataFilter,
}

impl EditCustomLocationFilter200ResponseData {
    pub fn new(uuid: uuid::Uuid, filter: models::EditCustomLocationFilter200ResponseDataFilter) -> EditCustomLocationFilter200ResponseData {
        EditCustomLocationFilter200ResponseData {
            uuid,
            filter,
        }
    }
}

