/*
 * ribbon-health
 *
 * An API for interacting with the data provided by Ribbon Health, including information about healthcare providers, locations, insurances, and more. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditCustomLocationFilter200Response {
    #[serde(rename = "data")]
    pub data: models::EditCustomLocationFilter200ResponseData,
}

impl EditCustomLocationFilter200Response {
    pub fn new(data: models::EditCustomLocationFilter200ResponseData) -> EditCustomLocationFilter200Response {
        EditCustomLocationFilter200Response {
            data,
        }
    }
}

