/*
 * ribbon-health
 *
 * An API for interacting with the data provided by Ribbon Health, including information about healthcare providers, locations, insurances, and more. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetCustomProviders400ResponseErrorMessage : An object representing what exactly went wrong. The keys available in this object vary with the type of error  returned.
/// An object representing what exactly went wrong. The keys available in this object vary with the type of error  returned.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetCustomProviders400ResponseErrorMessage {
    Object(serde_json::Value),
    String(String),
}

impl Default for GetCustomProviders400ResponseErrorMessage {
    fn default() -> Self {
        Self::Object(Default::default())
    }
}

