/*
 * ribbon-health
 *
 * An API for interacting with the data provided by Ribbon Health, including information about healthcare providers, locations, insurances, and more. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetCustomProviders200ResponseParametersExclusionsLanguage : Fuzzy search based on a string input (i.e. English) to exclude medical providers providers who speak / whose office staff speak the inputted language.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCustomProviders200ResponseParametersExclusionsLanguage {
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
    /// 
    #[serde(rename = "results", skip_serializing_if = "Option::is_none")]
    pub results: Option<Vec<String>>,
}

impl GetCustomProviders200ResponseParametersExclusionsLanguage {
    /// Fuzzy search based on a string input (i.e. English) to exclude medical providers providers who speak / whose office staff speak the inputted language.
    pub fn new() -> GetCustomProviders200ResponseParametersExclusionsLanguage {
        GetCustomProviders200ResponseParametersExclusionsLanguage {
            value: None,
            results: None,
        }
    }
}

