/*
 * ribbon-health
 *
 * An API for interacting with the data provided by Ribbon Health, including information about healthcare providers, locations, insurances, and more. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetEligibility200ResponseOutOfPocketDetailIndividualOutOfNetwork {
    /// The amount the member has paid towards their out-of-network out-of-pocket maximum, in dollars
    #[serde(rename = "spend", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub spend: Option<Option<String>>,
    /// The maximum amount the member can pay towards their out-of-network out-of-pocket maximum, in dollars
    #[serde(rename = "maximum", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub maximum: Option<Option<String>>,
    /// The remaining amount the member can pay towards their out-of-network out-of-pocket maximum, in dollars
    #[serde(rename = "remaining", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub remaining: Option<Option<String>>,
}

impl GetEligibility200ResponseOutOfPocketDetailIndividualOutOfNetwork {
    pub fn new() -> GetEligibility200ResponseOutOfPocketDetailIndividualOutOfNetwork {
        GetEligibility200ResponseOutOfPocketDetailIndividualOutOfNetwork {
            spend: None,
            maximum: None,
            remaining: None,
        }
    }
}

