/*
 * ribbon-health
 *
 * An API for interacting with the data provided by Ribbon Health, including information about healthcare providers, locations, insurances, and more. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPricingProviderProcedureLocation200ResponseParameters {
    #[serde(rename = "insurance", skip_serializing_if = "Option::is_none")]
    pub insurance: Option<models::GetCustomProviders200ResponseDataInnerInsurancesInner>,
}

impl GetPricingProviderProcedureLocation200ResponseParameters {
    pub fn new() -> GetPricingProviderProcedureLocation200ResponseParameters {
        GetPricingProviderProcedureLocation200ResponseParameters {
            insurance: None,
        }
    }
}

