/*
 * ribbon-health
 *
 * An API for interacting with the data provided by Ribbon Health, including information about healthcare providers, locations, insurances, and more. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPricingProviders200ResponseDataInnerMatchedLocationCostsOutpatientComponentsInner {
    /// The display name for this component of a procedure bundle.
    #[serde(rename = "display", skip_serializing_if = "Option::is_none")]
    pub display: Option<String>,
    /// The minimum cost for this component in this place of service, in dollars.
    #[serde(rename = "min", skip_serializing_if = "Option::is_none")]
    pub min: Option<f64>,
    /// The median cost for this component in this place of service, in dollars.
    #[serde(rename = "median", skip_serializing_if = "Option::is_none")]
    pub median: Option<f64>,
    /// The maximum cost for this component in this place of service, in dollars.
    #[serde(rename = "max", skip_serializing_if = "Option::is_none")]
    pub max: Option<f64>,
}

impl GetPricingProviders200ResponseDataInnerMatchedLocationCostsOutpatientComponentsInner {
    pub fn new() -> GetPricingProviders200ResponseDataInnerMatchedLocationCostsOutpatientComponentsInner {
        GetPricingProviders200ResponseDataInnerMatchedLocationCostsOutpatientComponentsInner {
            display: None,
            min: None,
            median: None,
            max: None,
        }
    }
}

