/*
 * ribbon-health
 *
 * An API for interacting with the data provided by Ribbon Health, including information about healthcare providers, locations, insurances, and more. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCustomProviders200Response {
    #[serde(rename = "parameters")]
    pub parameters: models::GetCustomProviders200ResponseParameters,
    /// 
    #[serde(rename = "data")]
    pub data: Vec<models::GetCustomProviders200ResponseDataInner>,
}

impl GetCustomProviders200Response {
    pub fn new(parameters: models::GetCustomProviders200ResponseParameters, data: Vec<models::GetCustomProviders200ResponseDataInner>) -> GetCustomProviders200Response {
        GetCustomProviders200Response {
            parameters,
            data,
        }
    }
}

