/*
 * ribbon-health
 *
 * An API for interacting with the data provided by Ribbon Health, including information about healthcare providers, locations, insurances, and more. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetProcedureCostEstimate200ResponseData {
    #[serde(rename = "cost_estimates", skip_serializing_if = "Option::is_none")]
    pub cost_estimates: Option<models::GetProcedureCostEstimate200ResponseDataCostEstimates>,
}

impl GetProcedureCostEstimate200ResponseData {
    pub fn new() -> GetProcedureCostEstimate200ResponseData {
        GetProcedureCostEstimate200ResponseData {
            cost_estimates: None,
        }
    }
}

