/*
 * ribbon-health
 *
 * An API for interacting with the data provided by Ribbon Health, including information about healthcare providers, locations, insurances, and more. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetOrganizations200ResponseParameters {
    /// The page of the results which was returned.
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<i32>,
    /// How many results are in each page.
    #[serde(rename = "page_size", skip_serializing_if = "Option::is_none")]
    pub page_size: Option<i32>,
    /// The total number of results matched, across all pages.
    #[serde(rename = "total_count", skip_serializing_if = "Option::is_none")]
    pub total_count: Option<i32>,
    /// The main criteria used to sort results in the record set.
    #[serde(rename = "sort_by", skip_serializing_if = "Option::is_none")]
    pub sort_by: Option<String>,
    /// The proximity radius of locations returned.
    #[serde(rename = "distance", skip_serializing_if = "Option::is_none")]
    pub distance: Option<i32>,
    #[serde(rename = "geo", skip_serializing_if = "Option::is_none")]
    pub geo: Option<models::GetCustomProviders200ResponseParametersGeo>,
    /// String input of an address that will be interpreted and geocoded in real time.
    #[serde(rename = "address", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub address: Option<Option<String>>,
    /// String input that is fuzzy matched to against the `organization.name` field.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl GetOrganizations200ResponseParameters {
    pub fn new() -> GetOrganizations200ResponseParameters {
        GetOrganizations200ResponseParameters {
            page: None,
            page_size: None,
            total_count: None,
            sort_by: None,
            distance: None,
            geo: None,
            address: None,
            name: None,
        }
    }
}

