/*
 * ribbon-health
 *
 * An API for interacting with the data provided by Ribbon Health, including information about healthcare providers, locations, insurances, and more. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetEligibilityInsurancePartners200Response {
    /// The total number of results matched.
    #[serde(rename = "count")]
    pub count: i32,
    /// 
    #[serde(rename = "data")]
    pub data: Vec<models::GetEligibilityInsurancePartners200ResponseDataInner>,
}

impl GetEligibilityInsurancePartners200Response {
    pub fn new(count: i32, data: Vec<models::GetEligibilityInsurancePartners200ResponseDataInner>) -> GetEligibilityInsurancePartners200Response {
        GetEligibilityInsurancePartners200Response {
            count,
            data,
        }
    }
}

