/*
 * ribbon-health
 *
 * An API for interacting with the data provided by Ribbon Health, including information about healthcare providers, locations, insurances, and more. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetProcedureCostEstimate200ResponseParameters {
    /// 
    #[serde(rename = "procedures", skip_serializing_if = "Option::is_none")]
    pub procedures: Option<Vec<models::GetCustomProviders200ResponseParametersProcedure>>,
    #[serde(rename = "member_zip", skip_serializing_if = "Option::is_none")]
    pub member_zip: Option<String>,
}

impl GetProcedureCostEstimate200ResponseParameters {
    pub fn new() -> GetProcedureCostEstimate200ResponseParameters {
        GetProcedureCostEstimate200ResponseParameters {
            procedures: None,
            member_zip: None,
        }
    }
}

