/*
 * ribbon-health
 *
 * An API for interacting with the data provided by Ribbon Health, including information about healthcare providers, locations, insurances, and more. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetEligibility200Response {
    #[serde(rename = "parameters")]
    pub parameters: models::GetEligibility200ResponseParameters,
    #[serde(rename = "status")]
    pub status: models::GetEligibility200ResponseStatus,
    /// A unique identifier for the given response which Ribbon can use to find it in our logs during support requests
    #[serde(rename = "request_id")]
    pub request_id: String,
    #[serde(rename = "plan_info", skip_serializing_if = "Option::is_none")]
    pub plan_info: Option<models::GetEligibility200ResponsePlanInfo>,
    #[serde(rename = "deductible_detail", skip_serializing_if = "Option::is_none")]
    pub deductible_detail: Option<models::GetEligibility200ResponseDeductibleDetail>,
    #[serde(rename = "out_of_pocket_detail", skip_serializing_if = "Option::is_none")]
    pub out_of_pocket_detail: Option<models::GetEligibility200ResponseOutOfPocketDetail>,
    #[serde(rename = "primary_care_summary", skip_serializing_if = "Option::is_none")]
    pub primary_care_summary: Option<models::GetEligibility200ResponsePrimaryCareSummary>,
    #[serde(rename = "dme_summary", skip_serializing_if = "Option::is_none")]
    pub dme_summary: Option<models::GetEligibility200ResponsePrimaryCareSummary>,
    #[serde(rename = "oncology_summary", skip_serializing_if = "Option::is_none")]
    pub oncology_summary: Option<models::GetEligibility200ResponsePrimaryCareSummary>,
    #[serde(rename = "vision_optometry_summary", skip_serializing_if = "Option::is_none")]
    pub vision_optometry_summary: Option<models::GetEligibility200ResponsePrimaryCareSummary>,
    #[serde(rename = "physical_therapy_summary", skip_serializing_if = "Option::is_none")]
    pub physical_therapy_summary: Option<models::GetEligibility200ResponsePrimaryCareSummary>,
    #[serde(rename = "specialist_office_summary", skip_serializing_if = "Option::is_none")]
    pub specialist_office_summary: Option<models::GetEligibility200ResponsePrimaryCareSummary>,
    #[serde(rename = "mental_health_summary", skip_serializing_if = "Option::is_none")]
    pub mental_health_summary: Option<models::GetEligibility200ResponsePrimaryCareSummary>,
    #[serde(rename = "surgical_summary", skip_serializing_if = "Option::is_none")]
    pub surgical_summary: Option<models::GetEligibility200ResponsePrimaryCareSummary>,
    #[serde(rename = "urgent_care_summary", skip_serializing_if = "Option::is_none")]
    pub urgent_care_summary: Option<models::GetEligibility200ResponsePrimaryCareSummary>,
    #[serde(rename = "diagnostic_lab_summary", skip_serializing_if = "Option::is_none")]
    pub diagnostic_lab_summary: Option<models::GetEligibility200ResponsePrimaryCareSummary>,
    #[serde(rename = "asc_facility_summary", skip_serializing_if = "Option::is_none")]
    pub asc_facility_summary: Option<models::GetEligibility200ResponsePrimaryCareSummary>,
    #[serde(rename = "chiropractic_summary", skip_serializing_if = "Option::is_none")]
    pub chiropractic_summary: Option<models::GetEligibility200ResponsePrimaryCareSummary>,
    #[serde(rename = "mri_ct_scan_summary", skip_serializing_if = "Option::is_none")]
    pub mri_ct_scan_summary: Option<models::GetEligibility200ResponsePrimaryCareSummary>,
    #[serde(rename = "x_ray_summary", skip_serializing_if = "Option::is_none")]
    pub x_ray_summary: Option<models::GetEligibility200ResponsePrimaryCareSummary>,
    #[serde(rename = "speech_therapy_summary", skip_serializing_if = "Option::is_none")]
    pub speech_therapy_summary: Option<models::GetEligibility200ResponsePrimaryCareSummary>,
    #[serde(rename = "occupational_therapy_summary", skip_serializing_if = "Option::is_none")]
    pub occupational_therapy_summary: Option<models::GetEligibility200ResponsePrimaryCareSummary>,
    #[serde(rename = "emergency_medical_summary", skip_serializing_if = "Option::is_none")]
    pub emergency_medical_summary: Option<models::GetEligibility200ResponsePrimaryCareSummary>,
    #[serde(rename = "wellness_or_routine_visit_summary", skip_serializing_if = "Option::is_none")]
    pub wellness_or_routine_visit_summary: Option<models::GetEligibility200ResponsePrimaryCareSummary>,
    #[serde(rename = "podiatry_office_summary", skip_serializing_if = "Option::is_none")]
    pub podiatry_office_summary: Option<models::GetEligibility200ResponsePrimaryCareSummary>,
    #[serde(rename = "outpatient_professional_summary", skip_serializing_if = "Option::is_none")]
    pub outpatient_professional_summary: Option<models::GetEligibility200ResponsePrimaryCareSummary>,
    #[serde(rename = "anesthesia_summary", skip_serializing_if = "Option::is_none")]
    pub anesthesia_summary: Option<models::GetEligibility200ResponsePrimaryCareSummary>,
    #[serde(rename = "substance_abuse_professional_summary", skip_serializing_if = "Option::is_none")]
    pub substance_abuse_professional_summary: Option<models::GetEligibility200ResponsePrimaryCareSummary>,
    #[serde(rename = "substance_abuse_in_patient_facility_summary", skip_serializing_if = "Option::is_none")]
    pub substance_abuse_in_patient_facility_summary: Option<models::GetEligibility200ResponsePrimaryCareSummary>,
    #[serde(rename = "substance_abuse_out_patient_facility_summary", skip_serializing_if = "Option::is_none")]
    pub substance_abuse_out_patient_facility_summary: Option<models::GetEligibility200ResponsePrimaryCareSummary>,
    #[serde(rename = "flu_vaccination_summary", skip_serializing_if = "Option::is_none")]
    pub flu_vaccination_summary: Option<models::GetEligibility200ResponsePrimaryCareSummary>,
    #[serde(rename = "hospital_inpatient_summary", skip_serializing_if = "Option::is_none")]
    pub hospital_inpatient_summary: Option<models::GetEligibility200ResponsePrimaryCareSummary>,
    #[serde(rename = "pharmacy_summary", skip_serializing_if = "Option::is_none")]
    pub pharmacy_summary: Option<models::GetEligibility200ResponsePrimaryCareSummary>,
    #[serde(rename = "hospital_outpatient_summary", skip_serializing_if = "Option::is_none")]
    pub hospital_outpatient_summary: Option<models::GetEligibility200ResponsePrimaryCareSummary>,
    #[serde(rename = "telemedicine_primary_care_summary", skip_serializing_if = "Option::is_none")]
    pub telemedicine_primary_care_summary: Option<models::GetEligibility200ResponsePrimaryCareSummary>,
    #[serde(rename = "telemedicine_specialist_summary", skip_serializing_if = "Option::is_none")]
    pub telemedicine_specialist_summary: Option<models::GetEligibility200ResponsePrimaryCareSummary>,
    #[serde(rename = "telemedicine_urgent_care_summary", skip_serializing_if = "Option::is_none")]
    pub telemedicine_urgent_care_summary: Option<models::GetEligibility200ResponsePrimaryCareSummary>,
    #[serde(rename = "telemedicine_physical_therapy_summary", skip_serializing_if = "Option::is_none")]
    pub telemedicine_physical_therapy_summary: Option<models::GetEligibility200ResponsePrimaryCareSummary>,
    #[serde(rename = "telemedicine_mental_health_summary", skip_serializing_if = "Option::is_none")]
    pub telemedicine_mental_health_summary: Option<models::GetEligibility200ResponsePrimaryCareSummary>,
    #[serde(rename = "psychotherapy_summary", skip_serializing_if = "Option::is_none")]
    pub psychotherapy_summary: Option<models::GetEligibility200ResponsePrimaryCareSummary>,
    #[serde(rename = "snf_summary", skip_serializing_if = "Option::is_none")]
    pub snf_summary: Option<models::GetEligibility200ResponsePrimaryCareSummary>,
    #[serde(rename = "snf_room_board_summary", skip_serializing_if = "Option::is_none")]
    pub snf_room_board_summary: Option<models::GetEligibility200ResponsePrimaryCareSummary>,
    #[serde(rename = "home_health_care_summary", skip_serializing_if = "Option::is_none")]
    pub home_health_care_summary: Option<models::GetEligibility200ResponsePrimaryCareSummary>,
    #[serde(rename = "hospice_summary", skip_serializing_if = "Option::is_none")]
    pub hospice_summary: Option<models::GetEligibility200ResponsePrimaryCareSummary>,
    #[serde(rename = "professional_physician_visit_inpatient_summary", skip_serializing_if = "Option::is_none")]
    pub professional_physician_visit_inpatient_summary: Option<models::GetEligibility200ResponsePrimaryCareSummary>,
}

impl GetEligibility200Response {
    pub fn new(parameters: models::GetEligibility200ResponseParameters, status: models::GetEligibility200ResponseStatus, request_id: String) -> GetEligibility200Response {
        GetEligibility200Response {
            parameters,
            status,
            request_id,
            plan_info: None,
            deductible_detail: None,
            out_of_pocket_detail: None,
            primary_care_summary: None,
            dme_summary: None,
            oncology_summary: None,
            vision_optometry_summary: None,
            physical_therapy_summary: None,
            specialist_office_summary: None,
            mental_health_summary: None,
            surgical_summary: None,
            urgent_care_summary: None,
            diagnostic_lab_summary: None,
            asc_facility_summary: None,
            chiropractic_summary: None,
            mri_ct_scan_summary: None,
            x_ray_summary: None,
            speech_therapy_summary: None,
            occupational_therapy_summary: None,
            emergency_medical_summary: None,
            wellness_or_routine_visit_summary: None,
            podiatry_office_summary: None,
            outpatient_professional_summary: None,
            anesthesia_summary: None,
            substance_abuse_professional_summary: None,
            substance_abuse_in_patient_facility_summary: None,
            substance_abuse_out_patient_facility_summary: None,
            flu_vaccination_summary: None,
            hospital_inpatient_summary: None,
            pharmacy_summary: None,
            hospital_outpatient_summary: None,
            telemedicine_primary_care_summary: None,
            telemedicine_specialist_summary: None,
            telemedicine_urgent_care_summary: None,
            telemedicine_physical_therapy_summary: None,
            telemedicine_mental_health_summary: None,
            psychotherapy_summary: None,
            snf_summary: None,
            snf_room_board_summary: None,
            home_health_care_summary: None,
            hospice_summary: None,
            professional_physician_visit_inpatient_summary: None,
        }
    }
}

