/*
 * ribbon-health
 *
 * An API for interacting with the data provided by Ribbon Health, including information about healthcare providers, locations, insurances, and more. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetNetworkAnalysis200ResponseParameters {
    /// A unique identifier for a single provider network from the Insurances reference endpoint.
    #[serde(rename = "insurance_id")]
    pub insurance_id: uuid::Uuid,
    /// The SSA codes the network analysis was run on.
    #[serde(rename = "ssa_codes")]
    pub ssa_codes: Vec<String>,
    /// How many unique NPIs accept the given insurance across all requested counties.
    #[serde(rename = "npi_count")]
    pub npi_count: i32,
}

impl GetNetworkAnalysis200ResponseParameters {
    pub fn new(insurance_id: uuid::Uuid, ssa_codes: Vec<String>, npi_count: i32) -> GetNetworkAnalysis200ResponseParameters {
        GetNetworkAnalysis200ResponseParameters {
            insurance_id,
            ssa_codes,
            npi_count,
        }
    }
}

