/*
 * ribbon-health
 *
 * An API for interacting with the data provided by Ribbon Health, including information about healthcare providers, locations, insurances, and more. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCustomProviders200ResponseDataInnerEducationsInnerEducation {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "uuid", skip_serializing_if = "Option::is_none")]
    pub uuid: Option<uuid::Uuid>,
}

impl GetCustomProviders200ResponseDataInnerEducationsInnerEducation {
    pub fn new() -> GetCustomProviders200ResponseDataInnerEducationsInnerEducation {
        GetCustomProviders200ResponseDataInnerEducationsInnerEducation {
            name: None,
            uuid: None,
        }
    }
}

