/*
 * ribbon-health
 *
 * An API for interacting with the data provided by Ribbon Health, including information about healthcare providers, locations, insurances, and more. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCustomProvider404ResponseError {
    #[serde(rename = "status")]
    pub status: i32,
    #[serde(rename = "code")]
    pub code: Code,
    #[serde(rename = "message")]
    pub message: Message,
}

impl GetCustomProvider404ResponseError {
    pub fn new(status: i32, code: Code, message: Message) -> GetCustomProvider404ResponseError {
        GetCustomProvider404ResponseError {
            status,
            code,
            message,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Code {
    #[serde(rename = "not_found")]
    NotFound,
}

impl Default for Code {
    fn default() -> Code {
        Self::NotFound
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Message {
    #[serde(rename = "resource not found")]
    ResourceNotFound,
}

impl Default for Message {
    fn default() -> Message {
        Self::ResourceNotFound
    }
}

