/*
 * ribbon-health
 *
 * An API for interacting with the data provided by Ribbon Health, including information about healthcare providers, locations, insurances, and more. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCustomProviders200ResponseParametersClinicalAreaIdsConditionsInner {
    /// A UUID uniquely identifying this condition
    #[serde(rename = "uuid", skip_serializing_if = "Option::is_none")]
    pub uuid: Option<uuid::Uuid>,
    #[serde(rename = "display", skip_serializing_if = "Option::is_none")]
    pub display: Option<String>,
    /// 
    #[serde(rename = "types", skip_serializing_if = "Option::is_none")]
    pub types: Option<Vec<Types>>,
    /// 
    #[serde(rename = "specialties", skip_serializing_if = "Option::is_none")]
    pub specialties: Option<Vec<models::GetCustomProviders200ResponseParametersSpecialty>>,
    /// 
    #[serde(rename = "modules", skip_serializing_if = "Option::is_none")]
    pub modules: Option<Vec<String>>,
}

impl GetCustomProviders200ResponseParametersClinicalAreaIdsConditionsInner {
    pub fn new() -> GetCustomProviders200ResponseParametersClinicalAreaIdsConditionsInner {
        GetCustomProviders200ResponseParametersClinicalAreaIdsConditionsInner {
            uuid: None,
            display: None,
            types: None,
            specialties: None,
            modules: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Types {
    #[serde(rename = "focus_areas")]
    FocusAreas,
    #[serde(rename = "condition_cost_estimate")]
    ConditionCostEstimate,
}

impl Default for Types {
    fn default() -> Types {
        Self::FocusAreas
    }
}

