/*
 * ribbon-health
 *
 * An API for interacting with the data provided by Ribbon Health, including information about healthcare providers, locations, insurances, and more. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCustomProviders200ResponseParametersProcedureProcedureCodesInner {
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl GetCustomProviders200ResponseParametersProcedureProcedureCodesInner {
    pub fn new() -> GetCustomProviders200ResponseParametersProcedureProcedureCodesInner {
        GetCustomProviders200ResponseParametersProcedureProcedureCodesInner {
            code: None,
            r#type: None,
            description: None,
        }
    }
}

