/*
 * ribbon-health
 *
 * An API for interacting with the data provided by Ribbon Health, including information about healthcare providers, locations, insurances, and more. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCustomProviders200ResponseParametersGeo {
    /// The latitude the search was focused on.
    #[serde(rename = "latitude", skip_serializing_if = "Option::is_none")]
    pub latitude: Option<f64>,
    /// The longitude the search was focused on.
    #[serde(rename = "longitude", skip_serializing_if = "Option::is_none")]
    pub longitude: Option<f64>,
}

impl GetCustomProviders200ResponseParametersGeo {
    pub fn new() -> GetCustomProviders200ResponseParametersGeo {
        GetCustomProviders200ResponseParametersGeo {
            latitude: None,
            longitude: None,
        }
    }
}

