/*
 * ribbon-health
 *
 * An API for interacting with the data provided by Ribbon Health, including information about healthcare providers, locations, insurances, and more. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetProcedureCostEstimate200Response {
    #[serde(rename = "parameters", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<models::GetProcedureCostEstimate200ResponseParameters>,
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<models::GetProcedureCostEstimate200ResponseData>,
}

impl GetProcedureCostEstimate200Response {
    pub fn new() -> GetProcedureCostEstimate200Response {
        GetProcedureCostEstimate200Response {
            parameters: None,
            data: None,
        }
    }
}

