/*
 * ribbon-health
 *
 * An API for interacting with the data provided by Ribbon Health, including information about healthcare providers, locations, insurances, and more. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetTins200ResponseTinsInner {
    /// Standard 9-digit identification code used by the IRS for business entities and used for contracting and paying provider/facility claims.
    #[serde(rename = "tin", skip_serializing_if = "Option::is_none")]
    pub tin: Option<String>,
    /// The billing entity name that appears on claims data, or if available, the official legal name of the billing entity.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The legal name of the entity associated with the TIN.
    #[serde(rename = "legal_name", skip_serializing_if = "Option::is_none")]
    pub legal_name: Option<String>,
    /// The address of the organization with the TIN. This could be the primary service location or billing location.
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    /// A yes/no field that assesses whether a TIN is likely to be valid or not. The field is powered by business logic that triangulates IRS data and claims data.
    #[serde(rename = "tin_confirmed", skip_serializing_if = "Option::is_none")]
    pub tin_confirmed: Option<bool>,
}

impl GetTins200ResponseTinsInner {
    pub fn new() -> GetTins200ResponseTinsInner {
        GetTins200ResponseTinsInner {
            tin: None,
            name: None,
            legal_name: None,
            address: None,
            tin_confirmed: None,
        }
    }
}

