/*
 * ribbon-health
 *
 * An API for interacting with the data provided by Ribbon Health, including information about healthcare providers, locations, insurances, and more. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPricingCarrierNames200Response {
    /// The name of the insurance carriers we have pricing data for
    #[serde(rename = "carriers", skip_serializing_if = "Option::is_none")]
    pub carriers: Option<Vec<String>>,
}

impl GetPricingCarrierNames200Response {
    pub fn new() -> GetPricingCarrierNames200Response {
        GetPricingCarrierNames200Response {
            carriers: None,
        }
    }
}

