/*
 * ribbon-health
 *
 * An API for interacting with the data provided by Ribbon Health, including information about healthcare providers, locations, insurances, and more. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetOrganizations200ResponseDataInnerPhoneNumbersInner {
    #[serde(rename = "phone", skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
    #[serde(rename = "detail", skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,
}

impl GetOrganizations200ResponseDataInnerPhoneNumbersInner {
    pub fn new() -> GetOrganizations200ResponseDataInnerPhoneNumbersInner {
        GetOrganizations200ResponseDataInnerPhoneNumbersInner {
            phone: None,
            detail: None,
        }
    }
}

