/*
 * ribbon-health
 *
 * An API for interacting with the data provided by Ribbon Health, including information about healthcare providers, locations, insurances, and more. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCustomProviders400ResponseError {
    /// The HTTP error code associated with this error
    #[serde(rename = "status")]
    pub status: i32,
    #[serde(rename = "code")]
    pub code: Code,
    #[serde(rename = "message")]
    pub message: models::GetCustomProviders400ResponseErrorMessage,
}

impl GetCustomProviders400ResponseError {
    pub fn new(status: i32, code: Code, message: models::GetCustomProviders400ResponseErrorMessage) -> GetCustomProviders400ResponseError {
        GetCustomProviders400ResponseError {
            status,
            code,
            message,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Code {
    #[serde(rename = "invalid_query_params")]
    InvalidQueryParams,
    #[serde(rename = "bad_request")]
    BadRequest,
}

impl Default for Code {
    fn default() -> Code {
        Self::InvalidQueryParams
    }
}

