/*
 * ribbon-health
 *
 * An API for interacting with the data provided by Ribbon Health, including information about healthcare providers, locations, insurances, and more. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPricingProviderProcedure200Response {
    #[serde(rename = "parameters")]
    pub parameters: models::GetPricingProviderProcedures200ResponseParameters,
    /// 
    #[serde(rename = "locations")]
    pub locations: Vec<models::GetPricingProviderProcedure200ResponseLocationsInner>,
}

impl GetPricingProviderProcedure200Response {
    pub fn new(parameters: models::GetPricingProviderProcedures200ResponseParameters, locations: Vec<models::GetPricingProviderProcedure200ResponseLocationsInner>) -> GetPricingProviderProcedure200Response {
        GetPricingProviderProcedure200Response {
            parameters,
            locations,
        }
    }
}

