/*
 * ribbon-health
 *
 * An API for interacting with the data provided by Ribbon Health, including information about healthcare providers, locations, insurances, and more. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCustomProviders200ResponseParametersLanguage {
    /// The languages that matched the given `language` parameter
    #[serde(rename = "results", skip_serializing_if = "Option::is_none")]
    pub results: Option<Vec<String>>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<serde_json::Value>>,
}

impl GetCustomProviders200ResponseParametersLanguage {
    pub fn new() -> GetCustomProviders200ResponseParametersLanguage {
        GetCustomProviders200ResponseParametersLanguage {
            results: None,
            value: None,
            description: None,
        }
    }
}

