/*
 * ribbon-health
 *
 * An API for interacting with the data provided by Ribbon Health, including information about healthcare providers, locations, insurances, and more. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCustomProviders200ResponseParametersProcedure {
    /// A UUID uniquely identifying this procedure
    #[serde(rename = "uuid", skip_serializing_if = "Option::is_none")]
    pub uuid: Option<uuid::Uuid>,
    #[serde(rename = "display", skip_serializing_if = "Option::is_none")]
    pub display: Option<String>,
    #[serde(rename = "procedure_code_count", skip_serializing_if = "Option::is_none")]
    pub procedure_code_count: Option<i32>,
    /// 
    #[serde(rename = "procedure_codes", skip_serializing_if = "Option::is_none")]
    pub procedure_codes: Option<Vec<models::GetCustomProviders200ResponseParametersProcedureProcedureCodesInner>>,
}

impl GetCustomProviders200ResponseParametersProcedure {
    pub fn new() -> GetCustomProviders200ResponseParametersProcedure {
        GetCustomProviders200ResponseParametersProcedure {
            uuid: None,
            display: None,
            procedure_code_count: None,
            procedure_codes: None,
        }
    }
}

