/*
 * ribbon-health
 *
 * An API for interacting with the data provided by Ribbon Health, including information about healthcare providers, locations, insurances, and more. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPricingProviderProcedures200ResponseParameters {
    /// The page of the results which was returned.
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<i32>,
    /// How many results are in each page.
    #[serde(rename = "page_size", skip_serializing_if = "Option::is_none")]
    pub page_size: Option<i32>,
    #[serde(rename = "insurance", skip_serializing_if = "Option::is_none")]
    pub insurance: Option<models::GetPricingProviderProcedures200ResponseParametersInsurance>,
}

impl GetPricingProviderProcedures200ResponseParameters {
    pub fn new() -> GetPricingProviderProcedures200ResponseParameters {
        GetPricingProviderProcedures200ResponseParameters {
            page: None,
            page_size: None,
            insurance: None,
        }
    }
}

