/*
 * ribbon-health
 *
 * An API for interacting with the data provided by Ribbon Health, including information about healthcare providers, locations, insurances, and more. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetOrganizations200ResponseDataInnerIdsInner {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "id_type", skip_serializing_if = "Option::is_none")]
    pub id_type: Option<String>,
}

impl GetOrganizations200ResponseDataInnerIdsInner {
    pub fn new() -> GetOrganizations200ResponseDataInnerIdsInner {
        GetOrganizations200ResponseDataInnerIdsInner {
            id: None,
            id_type: None,
        }
    }
}

