/*
 * ribbon-health
 *
 * An API for interacting with the data provided by Ribbon Health, including information about healthcare providers, locations, insurances, and more. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCustomProviders200ResponseDataInnerOnlineProfilesInner {
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl GetCustomProviders200ResponseDataInnerOnlineProfilesInner {
    pub fn new() -> GetCustomProviders200ResponseDataInnerOnlineProfilesInner {
        GetCustomProviders200ResponseDataInnerOnlineProfilesInner {
            url: None,
        }
    }
}

