/*
 * ribbon-health
 *
 * An API for interacting with the data provided by Ribbon Health, including information about healthcare providers, locations, insurances, and more. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPricingProviderProcedures200ResponseDataInner {
    /// The UUID of the procedure these prices correspond to.
    #[serde(rename = "uuid", skip_serializing_if = "Option::is_none")]
    pub uuid: Option<uuid::Uuid>,
    /// The name of the procedure these prices correspond to.
    #[serde(rename = "display", skip_serializing_if = "Option::is_none")]
    pub display: Option<String>,
    /// The minimum cost for this procedure with this provider, in dollars.
    #[serde(rename = "min_cost", skip_serializing_if = "Option::is_none")]
    pub min_cost: Option<f64>,
}

impl GetPricingProviderProcedures200ResponseDataInner {
    pub fn new() -> GetPricingProviderProcedures200ResponseDataInner {
        GetPricingProviderProcedures200ResponseDataInner {
            uuid: None,
            display: None,
            min_cost: None,
        }
    }
}

