/*
 * ribbon-health
 *
 * An API for interacting with the data provided by Ribbon Health, including information about healthcare providers, locations, insurances, and more. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPricingCarriers200ResponseDataInner {
    /// A UUID uniquely identifying this carrier
    #[serde(rename = "uuid", skip_serializing_if = "Option::is_none")]
    pub uuid: Option<uuid::Uuid>,
    /// A human-friendly name for this carrier
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// A month-granularity ISO-format date representing when we last updated price data for this carrier
    #[serde(rename = "last_updated", skip_serializing_if = "Option::is_none")]
    pub last_updated: Option<String>,
}

impl GetPricingCarriers200ResponseDataInner {
    pub fn new() -> GetPricingCarriers200ResponseDataInner {
        GetPricingCarriers200ResponseDataInner {
            uuid: None,
            name: None,
            last_updated: None,
        }
    }
}

