/*
 * ribbon-health
 *
 * An API for interacting with the data provided by Ribbon Health, including information about healthcare providers, locations, insurances, and more. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetEligibility200ResponsePrimaryCareSummaryInNetwork {
    /// The amount of the member's in-network copay, in dollars
    #[serde(rename = "copay", skip_serializing_if = "Option::is_none")]
    pub copay: Option<String>,
    #[serde(rename = "coinsurance", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub coinsurance: Option<Option<String>>,
}

impl GetEligibility200ResponsePrimaryCareSummaryInNetwork {
    pub fn new() -> GetEligibility200ResponsePrimaryCareSummaryInNetwork {
        GetEligibility200ResponsePrimaryCareSummaryInNetwork {
            copay: None,
            coinsurance: None,
        }
    }
}

