/*
 * ribbon-health
 *
 * An API for interacting with the data provided by Ribbon Health, including information about healthcare providers, locations, insurances, and more. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetEligibilityInsurancePartners200ResponseDataInner {
    /// Identifier for this insurance partner used by other endpoints in the Ribbon API
    #[serde(rename = "insurance_partner", skip_serializing_if = "Option::is_none")]
    pub insurance_partner: Option<String>,
    /// User-friendly display name for this insurance partner
    #[serde(rename = "display", skip_serializing_if = "Option::is_none")]
    pub display: Option<String>,
}

impl GetEligibilityInsurancePartners200ResponseDataInner {
    pub fn new() -> GetEligibilityInsurancePartners200ResponseDataInner {
        GetEligibilityInsurancePartners200ResponseDataInner {
            insurance_partner: None,
            display: None,
        }
    }
}

