/*
 * ribbon-health
 *
 * An API for interacting with the data provided by Ribbon Health, including information about healthcare providers, locations, insurances, and more. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCustomProviders200ResponseDataInnerLocationsInnerFaxesInner {
    #[serde(rename = "phone", skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
    #[serde(rename = "details", skip_serializing_if = "Option::is_none")]
    pub details: Option<String>,
    #[serde(rename = "confidence", skip_serializing_if = "Option::is_none")]
    pub confidence: Option<f64>,
}

impl GetCustomProviders200ResponseDataInnerLocationsInnerFaxesInner {
    pub fn new() -> GetCustomProviders200ResponseDataInnerLocationsInnerFaxesInner {
        GetCustomProviders200ResponseDataInnerLocationsInnerFaxesInner {
            phone: None,
            details: None,
            confidence: None,
        }
    }
}

