/*
 * ribbon-health
 *
 * An API for interacting with the data provided by Ribbon Health, including information about healthcare providers, locations, insurances, and more. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPricingProviders200Response {
    #[serde(rename = "parameters")]
    pub parameters: models::GetPricingProviders200ResponseParameters,
    /// All of the metadata on a specific provider plus a `matched_location` key showing the costs at the least expensive location.
    #[serde(rename = "data")]
    pub data: Vec<models::GetPricingProviders200ResponseDataInner>,
}

impl GetPricingProviders200Response {
    pub fn new(parameters: models::GetPricingProviders200ResponseParameters, data: Vec<models::GetPricingProviders200ResponseDataInner>) -> GetPricingProviders200Response {
        GetPricingProviders200Response {
            parameters,
            data,
        }
    }
}

