/*
 * ribbon-health
 *
 * An API for interacting with the data provided by Ribbon Health, including information about healthcare providers, locations, insurances, and more. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPricingProviderProcedures200ResponseParametersInsurance {
    /// A UUID uniquely identifying this insurance
    #[serde(rename = "uuid", skip_serializing_if = "Option::is_none")]
    pub uuid: Option<uuid::Uuid>,
    #[serde(rename = "display", skip_serializing_if = "Option::is_none")]
    pub display: Option<models::GetPricingProviderProcedures200ResponseParametersInsuranceDisplay>,
}

impl GetPricingProviderProcedures200ResponseParametersInsurance {
    pub fn new() -> GetPricingProviderProcedures200ResponseParametersInsurance {
        GetPricingProviderProcedures200ResponseParametersInsurance {
            uuid: None,
            display: None,
        }
    }
}

