/*
 * ribbon-health
 *
 * An API for interacting with the data provided by Ribbon Health, including information about healthcare providers, locations, insurances, and more. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PostCustomProviderTypeRequest : A JSON object mapping the name of the field to update to its new value
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostCustomProviderTypeRequest {
    #[serde(rename = "display_name", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
}

impl PostCustomProviderTypeRequest {
    /// A JSON object mapping the name of the field to update to its new value
    pub fn new() -> PostCustomProviderTypeRequest {
        PostCustomProviderTypeRequest {
            display_name: None,
        }
    }
}

