/*
 * ribbon-health
 *
 * An API for interacting with the data provided by Ribbon Health, including information about healthcare providers, locations, insurances, and more. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostCustomLocations201Response {
    #[serde(rename = "data")]
    pub data: models::GetCustomProvider200ResponseLocationsInner,
}

impl PostCustomLocations201Response {
    pub fn new(data: models::GetCustomProvider200ResponseLocationsInner) -> PostCustomLocations201Response {
        PostCustomLocations201Response {
            data,
        }
    }
}

