/*
 * ribbon-health
 *
 * An API for interacting with the data provided by Ribbon Health, including information about healthcare providers, locations, insurances, and more. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PutCustomLocationInsurances200ResponseData {
    /// A list of UUIDs to add to this location's set.
    #[serde(rename = "add", skip_serializing_if = "Option::is_none")]
    pub add: Option<Vec<uuid::Uuid>>,
    /// A list of UUIDs to remove to this location's set.
    #[serde(rename = "remove", skip_serializing_if = "Option::is_none")]
    pub remove: Option<Vec<uuid::Uuid>>,
    /// A list of UUIDs to remove to completely replace this location's set with. Not supported in combination with either `add` or `remove`.
    #[serde(rename = "override", skip_serializing_if = "Option::is_none")]
    pub r#override: Option<Vec<uuid::Uuid>>,
}

impl PutCustomLocationInsurances200ResponseData {
    pub fn new() -> PutCustomLocationInsurances200ResponseData {
        PutCustomLocationInsurances200ResponseData {
            add: None,
            remove: None,
            r#override: None,
        }
    }
}

