/*
 * ribbon-health
 *
 * An API for interacting with the data provided by Ribbon Health, including information about healthcare providers, locations, insurances, and more. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PutCustomLocation200ResponseData {
    /// An optional list of custom fields name to remove from the location
    #[serde(rename = "remove_fields", skip_serializing_if = "Option::is_none")]
    pub remove_fields: Option<Vec<String>>,
}

impl PutCustomLocation200ResponseData {
    pub fn new() -> PutCustomLocation200ResponseData {
        PutCustomLocation200ResponseData {
            remove_fields: None,
        }
    }
}

