/*
 * ribbon-health
 *
 * An API for interacting with the data provided by Ribbon Health, including information about healthcare providers, locations, insurances, and more. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PutCustomProviderRequest : A JSON object mapping the name of the field to update to its new value
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PutCustomProviderRequest {
    /// An optional list of custom fields name to remove.
    #[serde(rename = "remove_fields", skip_serializing_if = "Option::is_none")]
    pub remove_fields: Option<Vec<String>>,
}

impl PutCustomProviderRequest {
    /// A JSON object mapping the name of the field to update to its new value
    pub fn new() -> PutCustomProviderRequest {
        PutCustomProviderRequest {
            remove_fields: None,
        }
    }
}

